version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: backlog_postgres
    environment:
      - POSTGRES_USER=backlog_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-backlog_super_secure_password_2024}
      - POSTGRES_DB=student_planner
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "5433:5432"
    restart: unless-stopped
    networks:
      - backlog_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U backlog_user -d student_planner"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    container_name: backlog_backend
    environment:
      # Database
      - POSTGRES_USER=backlog_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-backlog_super_secure_password_2024}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=student_planner
      
      # JWT & Security
      - SECRET_KEY=${SECRET_KEY:-super-secret-dev-key-change-this}
      - ACCESS_TOKEN_EXPIRE_MINUTES=1440
      - DEBUG=true
      
      # CORS & URLs (для разработки)
      - BACKEND_CORS_ORIGINS=["http://localhost:3000", "http://localhost:3001"]
      - FRONTEND_URL=http://localhost:3000
      - BACKEND_URL=http://localhost:8000
      
      # VAPID Keys for Push Notifications - будут сгенерированы на сервере
      - VAPID_PRIVATE_KEY=
      - VAPID_PUBLIC_KEY=
      - VAPID_SUBJECT=mailto:admin@localhost
      
    volumes:
      - ./backend/uploads:/app/uploads
    ports:
      - "8000:8000"  # Прямое подключение для разработки
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - backlog_network
    restart: unless-stopped

  # Frontend для разработки
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: backlog_frontend
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
      - NEXT_PUBLIC_FRONTEND_URL=http://localhost:3000
      - NEXT_PUBLIC_VAPID_PUBLIC_KEY=  # Будет заполнен после генерации ключей
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - backlog_network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  backlog_network:
    driver: bridge 